# Generated by Django 6.0.6 on 2026-07-02 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
