# Generated by Django 6.0.6 on 2026-07-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_flow_flowstep'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='flowstep',
            constraint=models.UniqueConstraint(fields=('flow', 'order'), name='unique_flow_order'),
        ),
    ]
